name: Ubuntu Touch Build


on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
          sudo ln -sf python2.7 /usr/bin/python

      - name: Run build script
        run: ./build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-out
          path: out/*

  flashable:
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' }} # Manual trigger only
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download previous build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-out
          path: out

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y img2simg jq sudo wget xz-utils

      - name: Build flashable image
        run: |
          DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
          ./build/fetch-and-prepare-latest-ota.sh "16.04/arm64/android9/devel" "$DEVICE" ota
          mkdir -p out
          ./build/system-image-from-ota.sh ota/ubuntu_command out

      - name: Upload flashable artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flashable-out
          path: |
            out/boot.img
            out/system.img

  devel-flashable:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download previous build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-out
          path: out

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y img2simg jq sudo wget xz-utils

      - name: Build devel flashable image
        run: |
          DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
          ./build/prepare-fake-ota.sh out/device_${DEVICE}.tar.xz ota
          mkdir -p out
          ./build/system-image-from-ota.sh ota/ubuntu_command out

      - name: Upload devel flashable artifacts
        uses: actions/upload-artifact@v4
        with:
          name: devel-flashable-out
          path: |
            out/boot.img
            out/system.img

  devel-flashable-focal:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download previous build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-out
          path: out

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git img2simg jq sudo wget xz-utils

      - name: Build devel flashable (focal)
        run: |
          DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
          ROOTFS_URL="https://ci.ubports.com/job/focal-hybris-rootfs-arm64/job/master/lastSuccessfulBuild/artifact/ubuntu-touch-android9plus-rootfs-arm64.tar.gz" \
          ./build/prepare-fake-ota.sh out/device_${DEVICE}_usrmerge.tar.xz ota
          mkdir -p out
          ./build/system-image-from-ota.sh ota/ubuntu_command out

      - name: Upload focal devel flashable artifacts
        uses: actions/upload-artifact@v4
        with:
          name: devel-flashable-focal-out
          path: |
            out/boot.img
            out/system.img
